(()=>{'use strict';
const KEYS=['dark.timeline.project.v8','dark.timeline.project.v7','dark.timeline.project.v6','dark.timeline.project.v5'];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const WD=['SU','MO','TU','WE','TH','FR','SA'];
function getState(){for(const k of KEYS){try{const s=JSON.parse(localStorage.getItem(k)||'null');if(s&&typeof s==='object')return s}catch{}}return {events:[],tasks:[],notes:[],routines:[],projects:[]}}
function pad(n){return String(n).padStart(2,'0')}function parseISO(s){const [y,m,d]=String(s||'').split('-').map(Number);return{y:y||1970,m:m||1,d:d||1}}function icsDate(date,time='09:00'){const p=parseISO(date),[hh,mm]=String(time).split(':');return `${p.y}${pad(p.m)}${pad(p.d)}T${pad(+hh||0)}${pad(+mm||0)}00`}function addMinutes(date,time,min){const p=parseISO(date),[hh,mm]=String(time).split(':');const dt=new Date(p.y,p.m-1,p.d,+hh||0,+mm||0);dt.setMinutes(dt.getMinutes()+min);return `${dt.getFullYear()}${pad(dt.getMonth()+1)}${pad(dt.getDate())}T${pad(dt.getHours())}${pad(dt.getMinutes())}00`}function esc(s){return String(s||'').replace(/\\/g,'\\\\').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\n/g,'\\n')}
function download(n,c,t){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportIcs(){const st=getState(), now=new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';const out=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DarkTimeline//JP','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:Dark Timeline Planner'];
(st.events||[]).forEach(e=>out.push('BEGIN:VEVENT','UID:'+esc(e.id||crypto.randomUUID())+'@darktimeline','DTSTAMP:'+now,'DTSTART:'+icsDate(e.date,e.start),'DTEND:'+icsDate(e.date,e.end||e.start),'SUMMARY:'+esc(e.title),'DESCRIPTION:'+esc(e.memo),'END:VEVENT'));
(st.tasks||[]).forEach(t=>out.push('BEGIN:VTODO','UID:'+esc(t.id||crypto.randomUUID())+'@darktimeline','DTSTAMP:'+now,'DUE:'+icsDate(t.due,t.time),'SUMMARY:'+esc(t.title),'DESCRIPTION:'+esc((t.memo||'')+(t.minutes?' / '+t.minutes+'分':'')),'STATUS:'+(t.done?'COMPLETED':'NEEDS-ACTION'),'END:VTODO'));
(st.notes||[]).forEach(n=>out.push('BEGIN:VEVENT','UID:'+esc(n.id||crypto.randomUUID())+'@darktimeline','DTSTAMP:'+now,'DTSTART:'+icsDate(n.date,n.time||'21:00'),'DTEND:'+addMinutes(n.date,n.time||'21:00',15),'SUMMARY:'+esc(n.title||'メモ'),'DESCRIPTION:'+esc(n.text),'END:VEVENT'));
(st.routines||[]).forEach(r=>{const day=WD[+r.weekday||0];out.push('BEGIN:VEVENT','UID:'+esc(r.id||crypto.randomUUID())+'@darktimeline','DTSTAMP:'+now,'DTSTART:'+icsDate('2026-01-04',r.start||'08:00'),'DTEND:'+icsDate('2026-01-04',r.end||'08:30'),'RRULE:FREQ=WEEKLY;BYDAY='+day,'SUMMARY:'+esc(r.title),'DESCRIPTION:'+esc(r.memo||'曜日タスク'),'END:VEVENT')});
out.push('END:VCALENDAR');download('dark-timeline-calendar.ics',out.join('\r\n'),'text/calendar;charset=utf-8')}
document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('button');if(!b)return;const t=b.textContent.trim();if(t==='iCalendar出力'){e.preventDefault();e.stopPropagation();exportIcs()}},true);
let audioCtx=null, noiseNode=null;function toggleNoise(btn){if(noiseNode){try{noiseNode.stop();noiseNode.disconnect()}catch{}noiseNode=null;btn&&btn.classList.remove('v10-noise-on');return}audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=audioCtx.createBufferSource(),gain=audioCtx.createGain();gain.gain.value=.035;src.buffer=buffer;src.loop=true;src.connect(gain).connect(audioCtx.destination);src.start();noiseNode=src;btn&&btn.classList.add('v10-noise-on')}
function patchFocus(){if(!/集中/.test($('#title')?.textContent||''))return;if($('[data-v10-noise]'))return;const rows=$$('.card .row');const row=rows[0];if(row){row.append(Object.assign(document.createElement('button'),{textContent:'ホワイトノイズ'}));row.lastChild.setAttribute('data-v10-noise','1');row.lastChild.addEventListener('click',()=>toggleNoise(row.lastChild))}}
function patchText(){document.querySelectorAll('p,.muted').forEach(n=>{const t=n.textContent||'';if(t.includes('今日はまだ空です')||t.includes('六曜は参考表示')||t.includes('日曜は薄赤'))n.classList.add('v10-hidden')});document.querySelectorAll('.rokuyo').forEach(n=>n.remove());document.querySelectorAll('button').forEach(b=>{const t=b.textContent.trim();if(t==='ホーム画面に追加'||t==='追加'||t==='手順')b.classList.add('v10-hidden');if((t==='メモ追加'||t==='メモ保存')&&b.previousElementSibling&&b.previousElementSibling.classList.contains('memoBox'))b.classList.add('v10-note-button-fix')})}
function addProjectTextTool(){if(!/プロジェクト/.test($('#title')?.textContent||''))return;if($('#v10TextPlan'))return;const main=$('#view');if(!main)return;const sec=document.createElement('section');sec.className='card';sec.id='v10TextPlan';sec.innerHTML='<h2>文字ベースの日割り</h2><div class="v10-project-tool"><label>プロジェクト名<input id="v10pTitle" value="レポート"></label><div class="v10-small-grid"><label>開始日<input id="v10pStart" type="date"></label><label>締切日<input id="v10pDue" type="date"></label></div><div class="v10-small-grid"><label>総時間<input id="v10pHours" type="number" value="10"></label><label>バッファー%<input id="v10pBuffer" type="number" value="20"></label></div><label>作業フェーズ<textarea id="v10pPhases">調査\n構成\n作成\n修正\n提出準備</textarea></label><button id="v10pMake" class="primary">文字で日割り作成</button><pre id="v10pOut" class="v10-text-plan">ここに日割り案を表示します。</pre></div>';main.prepend(sec);const td=new Date(),iso=`${td.getFullYear()}-${pad(td.getMonth()+1)}-${pad(td.getDate())}`;sec.querySelector('#v10pStart').value=iso;td.setDate(td.getDate()+14);sec.querySelector('#v10pDue').value=`${td.getFullYear()}-${pad(td.getMonth()+1)}-${pad(td.getDate())}`;sec.querySelector('#v10pMake').addEventListener('click',()=>{const title=sec.querySelector('#v10pTitle').value||'Project',start=sec.querySelector('#v10pStart').value,due=sec.querySelector('#v10pDue').value,h=(+sec.querySelector('#v10pHours').value||1)*60,buf=+sec.querySelector('#v10pBuffer').value||0,ph=sec.querySelector('#v10pPhases').value.split('\n').map(x=>x.trim()).filter(Boolean);let days=[],d=new Date(start+'T00:00:00'),end=new Date(due+'T00:00:00');while(d<end){days.push(new Date(d));d.setDate(d.getDate()+1)}const b=Math.floor(days.length*buf/100),work=days.slice(0,Math.max(1,days.length-b)),per=Math.ceil(h/work.length);let lines=[`【${title}】文字ベース日割り案`,`作業日 ${work.length}日 / 予備日 ${b}日 / 1日 ${per}分`,'' ];work.forEach((x,i)=>lines.push(`${x.getMonth()+1}/${x.getDate()} ${ph[i%ph.length]} ${per}分`));days.slice(work.length).forEach((x,i)=>lines.push(`${x.getMonth()+1}/${x.getDate()} 予備日 ${i+1}`));lines.push(`${due} 提出日`);sec.querySelector('#v10pOut').textContent=lines.join('\n')})}
const mo=new MutationObserver(()=>{patchText();patchFocus();addProjectTextTool()});mo.observe(document.body,{childList:true,subtree:true});setInterval(()=>{patchText();patchFocus();addProjectTextTool()},800);patchText();
})();