(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function pad(n){return String(n).padStart(2,'0')}function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function patchMemo(){document.querySelectorAll('.memoBox').forEach(box=>{box.classList.add('v11-memo-wrap');box.querySelectorAll('input,textarea').forEach(i=>i.placeholder='')});document.querySelectorAll('button').forEach(b=>{const t=b.textContent.trim();if(t==='メモ追加'||t==='メモ保存'){b.classList.add('v11-memo-button');if(b.previousElementSibling&&b.previousElementSibling.classList.contains('memoBox'))b.previousElementSibling.after(b)}})}
function setTimerClick(label){const btn=$$('button').find(b=>b.textContent.trim()===label);if(btn)btn.click()}
function patchFocus(){if(!/集中/.test($('#title')?.textContent||''))return;if($('[data-v11-5217]'))return;const row=$$('.card .row')[0];if(!row)return;const b=document.createElement('button');b.textContent='52/17';b.className='v11-rule-btn';b.setAttribute('data-v11-5217','1');b.addEventListener('click',()=>{setTimerClick('一時停止');const workBtn=$$('button').find(x=>x.textContent.trim().startsWith('作業'));if(workBtn){/* existing timer API is internal, use UI fallback */} const custom=document.createElement('button');custom.style.display='none';document.body.append(custom); // fallback by direct state is not exposed; simulate through injected global-free custom timer
 window.__v11_5217_mode='作業52'; window.__v11_5217_remain=52*60; start5217();});row.append(b)}
let t5217=null;function start5217(){clearInterval(t5217);render5217();t5217=setInterval(()=>{window.__v11_5217_remain--;if(window.__v11_5217_remain<=0){window.__v11_5217_mode=window.__v11_5217_mode==='作業52'?'休憩17':'作業52';window.__v11_5217_remain=(window.__v11_5217_mode==='作業52'?52:17)*60}render5217()},1000)}function render5217(){if(!/集中/.test($('#title')?.textContent||''))return;const timer=$('.timer'),modeEl=$('.timerMode'),bar=$('.bigProgress .bar');if(!timer||!modeEl)return;const r=window.__v11_5217_remain??0,mode=window.__v11_5217_mode||'作業52',base=mode==='作業52'?52*60:17*60;modeEl.textContent=mode+' ルール';timer.textContent=`${pad(Math.floor(r/60))}:${pad(r%60)}`;if(bar)bar.style.width=`${100-r/base*100}%`}
function addCharTool(){if(!/プロジェクト/.test($('#title')?.textContent||''))return;if($('#v11CharPlan'))return;const main=$('#view');if(!main)return;const sec=document.createElement('section');sec.className='card';sec.id='v11CharPlan';sec.innerHTML='<h2>文字数ベースの日割り</h2><div class="v11-char-tool"><label>プロジェクト名<input id="v11cTitle" value="レポート"></label><div class="v11-char-grid"><label>開始日<input id="v11cStart" type="date"></label><label>締切日<input id="v11cDue" type="date"></label></div><div class="v11-char-grid"><label>目標文字数<input id="v11cChars" type="number" value="4000"></label><label>バッファー%<input id="v11cBuffer" type="number" value="20"></label></div><label>作業しない曜日<textarea id="v11cOff">日</textarea></label><button id="v11cMake" class="primary">文字数で日割り作成</button><pre id="v11cOut" class="v11-char-output">ここに文字数ベースの日割り案を表示します。</pre></div>';main.prepend(sec);const now=new Date();sec.querySelector('#v11cStart').value=iso(now);const due=new Date(now);due.setDate(due.getDate()+14);sec.querySelector('#v11cDue').value=iso(due);sec.querySelector('#v11cMake').addEventListener('click',()=>{const title=$('#v11cTitle').value||'Project',start=$('#v11cStart').value,due=$('#v11cDue').value,total=+$('#v11cChars').value||1000,buf=+$('#v11cBuffer').value||0,off=$('#v11cOff').value;const offNums=['日','月','火','水','木','金','土'].map((w,i)=>off.includes(w)?i:null).filter(x=>x!==null);let days=[],d=new Date(start+'T00:00:00'),end=new Date(due+'T00:00:00');while(d<end){if(!offNums.includes(d.getDay()))days.push(new Date(d));d.setDate(d.getDate()+1)}const bufferDays=Math.floor(days.length*buf/100),work=days.slice(0,Math.max(1,days.length-bufferDays)),per=Math.ceil(total/work.length);let remain=total;let lines=[`【${title}】文字数ベース日割り案`,`目標 ${total.toLocaleString()}字 / 作業日 ${work.length}日 / 予備日 ${bufferDays}日`,`1日目安 約${per.toLocaleString()}字`,'' ];work.forEach((x,i)=>{const n=Math.min(per,remain);remain-=n;lines.push(`${x.getMonth()+1}/${x.getDate()} ${n.toLocaleString()}字（累計 ${Math.min(total,total-remain).toLocaleString()}字）`)});days.slice(work.length).forEach((x,i)=>lines.push(`${x.getMonth()+1}/${x.getDate()} 予備日 ${i+1}：不足分・推敲・整形`));lines.push(`${due} 提出日`);$('#v11cOut').textContent=lines.join('\n')})}
function patch(){patchMemo();patchFocus();addCharTool()}
const mo=new MutationObserver(patch);mo.observe(document.body,{childList:true,subtree:true});setInterval(patch,700);patch();
})();