(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const pad=n=>String(n).padStart(2,'0'); const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function titleText(){return ($('#title')?.textContent||'').trim()}
function patchMemo(){
  document.querySelectorAll('.memoBox').forEach(box=>{
    box.classList.add('v12-memo-clean');
    box.querySelectorAll('input,textarea').forEach(i=>{i.placeholder=''; i.style.width='100%'; i.style.maxWidth='100%'});
    box.querySelectorAll('.field').forEach(f=>{f.style.width='100%'; f.style.maxWidth='100%'})
  });
  document.querySelectorAll('button').forEach(b=>{const t=b.textContent.trim(); if(t==='メモ追加'||t==='メモ保存'){b.classList.add('v12-memo-btn')}});
}
let v12={mode:'ポモドーロ',label:'作業25',remain:25*60,base:25*60,timer:null,noise:null,audio:null};
function setV12(minutes,label,mode){clearInterval(v12.timer);v12.timer=null;v12.mode=mode;v12.label=label;v12.remain=minutes*60;v12.base=minutes*60;renderV12()}
function startV12(){clearInterval(v12.timer);v12.timer=setInterval(()=>{v12.remain--; if(v12.remain<=0){if(v12.mode==='52/17'){setV12(v12.label==='作業52'?17:52, v12.label==='作業52'?'休憩17':'作業52','52/17'); startV12()}else{setV12(v12.label.startsWith('作業')?5:25, v12.label.startsWith('作業')?'短休憩5':'作業25','ポモドーロ'); startV12()}} renderV12()},1000)}
function pauseV12(){clearInterval(v12.timer);v12.timer=null}
function toggleNoise(btn){if(v12.noise){try{v12.noise.stop();v12.noise.disconnect()}catch{}v12.noise=null;btn.classList.remove('v12-noise-on');return}v12.audio=v12.audio||new(window.AudioContext||window.webkitAudioContext)();const buffer=v12.audio.createBuffer(1,v12.audio.sampleRate*2,v12.audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=v12.audio.createBufferSource(),gain=v12.audio.createGain();gain.gain.value=.035;src.buffer=buffer;src.loop=true;src.connect(gain).connect(v12.audio.destination);src.start();v12.noise=src;btn.classList.add('v12-noise-on')}
function renderV12(){const card=$('#v12FocusCard'); if(!card)return;card.querySelector('.v12-mode').textContent=`${v12.mode} / ${v12.label}`;card.querySelector('.v12-timer').textContent=`${pad(Math.floor(v12.remain/60))}:${pad(v12.remain%60)}`;card.querySelector('.v12-bar').style.width=`${Math.max(0,Math.min(100,100-v12.remain/v12.base*100))}%`;card.querySelectorAll('[data-v12-mode]').forEach(b=>b.classList.toggle('v12-active',b.dataset.v12Mode===v12.label))}
function ensureFocus(){if(titleText()!=='集中')return;const main=$('#view'); if(!main||$('#v12FocusCard'))return; const card=document.createElement('section');card.id='v12FocusCard';card.className='v12-focus-card';card.innerHTML='<div class="v12-focus-title">集中タイマー</div><div class="v12-mode"></div><div class="v12-timer"></div><div class="v12-progress"><div class="v12-bar"></div></div><div class="v12-row"><button class="primary" id="v12Start">開始</button><button id="v12Pause">一時停止</button><button id="v12Reset">リセット</button><button data-v12-mode="作業25">25/5</button><button data-v12-mode="作業52">52/17</button><button id="v12Noise">ホワイトノイズ</button></div>';main.prepend(card);card.querySelector('#v12Start').onclick=startV12;card.querySelector('#v12Pause').onclick=pauseV12;card.querySelector('#v12Reset').onclick=()=>setV12(v12.label==='作業52'||v12.label==='休憩17'?(v12.label==='休憩17'?17:52):(v12.label.startsWith('短')?5:25),v12.label,v12.mode);card.querySelector('[data-v12-mode="作業25"]').onclick=()=>setV12(25,'作業25','ポモドーロ');card.querySelector('[data-v12-mode="作業52"]').onclick=()=>setV12(52,'作業52','52/17');card.querySelector('#v12Noise').onclick=()=>toggleNoise(card.querySelector('#v12Noise'));renderV12()}
function ensureCharTool(){if(titleText()!=='プロジェクト')return;if($('#v12CharPlan'))return;const main=$('#view');if(!main)return;const sec=document.createElement('section');sec.className='v12-char-card';sec.id='v12CharPlan';sec.innerHTML='<h2>文字数ベースの日割り</h2><div class="v12-char-tool"><label>プロジェクト名<input id="v12cTitle" value="レポート"></label><div class="v12-char-grid"><label>開始日<input id="v12cStart" type="date"></label><label>締切日<input id="v12cDue" type="date"></label></div><div class="v12-char-grid"><label>目標文字数<input id="v12cChars" type="number" value="4000"></label><label>バッファー%<input id="v12cBuffer" type="number" value="20"></label></div><label>作業しない曜日<textarea id="v12cOff">日</textarea></label><button id="v12cMake" class="primary">文字数で日割り作成</button><pre id="v12cOut" class="v12-char-output">ここに文字数ベースの日割り案を表示します。</pre></div>';main.prepend(sec);const now=new Date();$('#v12cStart').value=iso(now);const due=new Date(now);due.setDate(due.getDate()+14);$('#v12cDue').value=iso(due);$('#v12cMake').onclick=()=>{const title=$('#v12cTitle').value||'Project',start=$('#v12cStart').value,due=$('#v12cDue').value,total=+$('#v12cChars').value||1000,buf=+$('#v12cBuffer').value||0,off=$('#v12cOff').value;const offNums=['日','月','火','水','木','金','土'].map((w,i)=>off.includes(w)?i:null).filter(x=>x!==null);let days=[],d=new Date(start+'T00:00:00'),end=new Date(due+'T00:00:00');while(d<end){if(!offNums.includes(d.getDay()))days.push(new Date(d));d.setDate(d.getDate()+1)}const bufferDays=Math.floor(days.length*buf/100),work=days.slice(0,Math.max(1,days.length-bufferDays)),per=Math.ceil(total/work.length);let remain=total;let lines=[`【${title}】文字数ベース日割り案`,`目標 ${total.toLocaleString()}字 / 作業日 ${work.length}日 / 予備日 ${bufferDays}日`,`1日目安 約${per.toLocaleString()}字`,'' ];work.forEach(x=>{const n=Math.min(per,remain);remain-=n;lines.push(`${x.getMonth()+1}/${x.getDate()} ${n.toLocaleString()}字（累計 ${(total-remain).toLocaleString()}字）`)});days.slice(work.length).forEach((x,i)=>lines.push(`${x.getMonth()+1}/${x.getDate()} 予備日 ${i+1}：不足分・推敲・整形`));lines.push(`${due} 提出日`);$('#v12cOut').textContent=lines.join('\n')}}
function patch(){patchMemo();ensureFocus();ensureCharTool()}
new MutationObserver(patch).observe(document.body,{childList:true,subtree:true});setInterval(patch,500);patch();
})();